server:
  port: 8888

spring:
  application:
    name: gatewayserver

  cloud:
    config:
      enabled: false     # No config server
    discovery:
      enabled: true      # Enable Eureka discovery

    gateway:
      routes:
        - id: theme-ms
          uri: lb://theme
          predicates:
            - Path=/api/themes/**
        - id: teachers-ms
          uri: lb://formation
          predicates:
            - Path=/api/formations/**
        - id: theme-ms2
          uri: lb://theme
          predicates:
            - Path=/api/themes/**


# Eureka configuration should be at ROOT level, not under spring
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true    # Set to false for Docker

management:
  endpoints:
    web:
      exposure:
        include: '*'     # Expose actuator endpoints
  endpoint:
    gateway:
      enabled: true